networks:
  service_net:
    external: true

services:
  fpm:
    build:
      context: ./.docker
      dockerfile: Dockerfile
    image: fpm
    container_name: fpm
    ports:
      - 5173:5173
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    networks:
      - service_net

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_USER: user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    networks:
      - service_net

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - service_net
